/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class richard_ztesoft_com_encrypttest_ndk_KeyProvider */

#ifndef _Included_richard_ztesoft_com_encrypttest_ndk_KeyProvider
#define _Included_richard_ztesoft_com_encrypttest_ndk_KeyProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     richard_ztesoft_com_encrypttest_ndk_KeyProvider
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_richard_ztesoft_com_encrypttest_ndk_KeyProvider_getKeyValue
  (JNIEnv *, jclass);

/*
 * Class:     richard_ztesoft_com_encrypttest_ndk_KeyProvider
 * Method:    getIV
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_richard_ztesoft_com_encrypttest_ndk_KeyProvider_getIV
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
